name: windows build


on:
  # enable triggers on main later

  # pull_request:
  #   types: [opened, review_requested]
  #   branches: [main]
  push:
    branches:
    # - 'main'
    - 'ghub-workflow'
env:
  BUILD_TYPE: Release

jobs:
  windows-build:
    runs-on: windows-latest
    steps:

    - name: checkout
      uses: actions/checkout/@v3
      with:
        submodules: recursive

    - name: configure cmake
      run: cmake -DCMAKE_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} -S${{github.workspace}} -B${{github.workspace}}/build

    - name: cmake build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

